### ISSUE TITLE
[Bug] JSON plugin can not fetch fields that are next to a nested JSON object

### ISSUE THREAD

**Issue by rickstaa** [yesoreyeram/grafana-infinity-datasource#285]
**Describe the bug**

For my Grafana dashboard, I am trying to fetch some data from [this API endpoint](https://api-eu.livepool.io/api/v1/transcoders). The response returned by this endpoint is as follows:

```json
{
  "0x455a304a1d3342844f4dd36731f8da066efdd30b": {
    "Nodes": [
      {
        "Address": "86.95.103.245:46044",
        "Capacity": 5,
        "Load": 0,
        "EthereumAddress": "0x455a304a1d3342844f4dd36731f8da066efdd30b"
      }
    ],
    "Pending": 215919916032240,
    "Payout": 0,
    "Region": "EU"
  },
  "0x48b988eb13a4fabddc82d4b632ccb49d30b7c543": {
    "Nodes": [
      {
        "Address": "78.62.181.179:63447",
        "Capacity": 5,
        "Load": 0,
        "EthereumAddress": "0x48b988eb13a4fabddc82d4b632ccb49d30b7c543"
      }
    ],
    "Pending": 1128157165764810,
    "Payout": 0,
    "Region": "EU"
  }
}
```

I would like to display the `Pending` and `Payout` values on my dashboard but I am not able to get them to show up in Grafana. I can get into the `0x455a304a1d3342844f4dd36731f8da066efdd30b` field by using the `Rows / Root` argument. When I do this however it only shows me the variables contained in the `Nodes` field (i.e. `Address`, `Capacity`, `Load` and `EthereumAddress`):

![image](https://user-images.githubusercontent.com/17570430/159433732-77749c7f-2e59-465a-af30-58670c4311c9.png)

The other fields that are not nested in the `Nodes` field do not show up (i.e. `Pending`, `Payout` and `Region`). I can get these fields to show up by selecting the `Is data in columnar format?` in the `Advanced JSON parsing options` section:

![image](https://user-images.githubusercontent.com/17570430/159441781-176f1c0c-44d6-46be-9858-dddc840cf8bd.png)

Unfortunately when using this option the data from the `Payout` and `Pending` fields show up as `null`:

![image](https://user-images.githubusercontent.com/17570430/159441865-50af02b4-cc93-4c4b-afa7-b33687aa9ecc.png)

**Version Details:**

- **Grafana version:** 8.4.3
- **Plugin version :** 0.8.3

**Comment by yesoreyeram** [comment]
With the current version you are using, you can't achieve that.

But with v0.8.7, the plugin have support for this via UQL. So instead of json use UQL and `project kv()` method.

hope this helps.

Example : [query](https://grafana-infinity-datasource.herokuapp.com/explore?orgId=1&left=%7B%22datasource%22:%22Infinity%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22type%22:%22uql%22,%22source%22:%22url%22,%22format%22:%22table%22,%22url%22:%22https:%2F%2Fapi-eu.livepool.io%2Fapi%2Fv1%2Ftranscoders%22,%22url_options%22:%7B%22method%22:%22GET%22,%22data%22:%22%22%7D,%22root_selector%22:%22%22,%22columns%22:%5B%5D,%22filters%22:%5B%5D,%22global_query_id%22:%22%22,%22uql%22:%22parse-json%5Cn%7C%20project%20kv()%5Cn%7C%20project%20%5C%22Region%5C%22%3D%5C%22value.Region%5C%22,%5C%22Payout%5C%22%3D%5C%22value.Payout%5C%22,%20%5C%22Pending%5C%22%3D%5C%22value.Pending%5C%22,%20%5C%22Nodes%5C%22%3D%5C%22value.Nodes%5C%22%5Cn%7C%20mv-expand%20%5C%22Node%5C%22%3D%5C%22Nodes%5C%22%5Cn%7C%20project%20%5C%22Region%5C%22,%20%5C%22Payout%5C%22,%20%5C%22Pending%5C%22,%20%5C%22NodeAddress%5C%22%3D%5C%22Node.Address%5C%22,%20%5C%22NodeCapacity%5C%22%3D%5C%22Node.Capacity%5C%22,%20%5C%22EthereumAddress%5C%22%3D%5C%22Node.EthereumAddress%5C%22%5Cn%7C%20order%20by%20%5C%22NodeCapacity%5C%22%20desc%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/153843/164212168-fea21cb1-8ae4-4248-82a8-1ab9b2334d35.png">

**Comment by rickstaa** [comment]
@yesoreyeram Amazing thanks so much for creating this plugin.
